"""
Abstract Base Provider for AI Model Integration.

Defines the interface that all AI providers must implement.
Every provider (Gemini, Ollama, OpenAI, Qwen) inherits from BaseProvider
and implements the required abstract methods.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, AsyncGenerator, Dict, List, Optional


@dataclass
class ModelInfo:
    """Information about an AI model offered by a provider."""

    id: str
    name: str
    description: str = ""
    max_tokens: int = 4096
    supports_streaming: bool = True
    supports_system_prompt: bool = True
    pricing_per_1k_tokens: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ProviderConfig:
    """Configuration for an AI provider instance."""

    name: str
    display_name: str = ""
    api_key: Optional[str] = None
    base_url: Optional[str] = None
    default_model: str = ""
    models: List[str] = field(default_factory=list)
    timeout: int = 60
    max_retries: int = 3
    extra: Dict[str, Any] = field(default_factory=dict)


@dataclass
class GenerationRequest:
    """Request parameters for model generation."""

    model: str
    messages: List[Dict[str, str]]
    system_prompt: Optional[str] = None
    temperature: float = 0.7
    max_tokens: Optional[int] = None
    top_p: float = 0.95
    top_k: int = 40
    stop_sequences: Optional[List[str]] = None
    extra: Dict[str, Any] = field(default_factory=dict)


@dataclass
class GenerationResponse:
    """Response from a model generation call."""

    content: str
    model: str
    provider: str
    finish_reason: str = "stop"
    tokens_prompt: Optional[int] = None
    tokens_completion: Optional[int] = None
    tokens_total: Optional[int] = None
    latency_ms: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class HealthStatus:
    """Health check result for a provider."""

    available: bool
    provider: str
    latency_ms: Optional[float] = None
    models_available: int = 0
    error: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseProvider(ABC):
    """Abstract base class for all AI providers.

    Every provider must implement the four core abstract methods:
        - generate()
        - stream()
        - health_check()
        - list_models()

    Providers should never be called directly by application code.
    Communicate only through AIManager.
    """

    def __init__(self, config: ProviderConfig):
        self._config = config
        self._name = config.name

    # ------------------------------------------------------------------ #
    # Properties
    # ------------------------------------------------------------------ #

    @property
    def name(self) -> str:
        """Get the provider name."""
        return self._name

    @property
    def config(self) -> ProviderConfig:
        """Get the provider configuration."""
        return self._config

    # ------------------------------------------------------------------ #
    # Abstract Methods — Must Implement
    # ------------------------------------------------------------------ #

    @abstractmethod
    async def generate(self, request: GenerationRequest) -> GenerationResponse:
        """Generate a complete (non-streaming) response from the model.

        Args:
            request: Generation parameters including model, messages, etc.

        Returns:
            GenerationResponse containing the model's output and metadata.

        Raises:
            ProviderUnavailableError: If the provider cannot be reached.
            InvalidModelError: If the requested model is unsupported.
            InvalidApiKeyError: If authentication fails.
            RateLimitError: If provider rate limits are exceeded.
        """
        ...

    @abstractmethod
    async def stream(
        self, request: GenerationRequest
    ) -> AsyncGenerator[str, None]:
        """Stream a response from the model token by token.

        Args:
            request: Generation parameters including model, messages, etc.

        Yields:
            Content tokens as they are generated by the model.

        Raises:
            Same as generate().
        """
        ...
        # Deliberately empty — yield is abstract; subclasses must implement
        # a generator with `yield` statements.
        # The `...` (Ellipsis) satisfies the abstract requirement.
        if False:
            yield ""  # pragma: no cover — trick so Python sees this as a generator

    @abstractmethod
    async def health_check(self) -> HealthStatus:
        """Check if the provider is operational.

        Returns:
            HealthStatus indicating availability and diagnostic info.
        """
        ...

    @abstractmethod
    async def list_models(self) -> List[ModelInfo]:
        """List all available models from this provider.

        Returns:
            List of ModelInfo describing each available model.
        """
        ...

    # ------------------------------------------------------------------ #
    # Optional Override — Default Implementation
    # ------------------------------------------------------------------ #

    async def chat(self, request: GenerationRequest) -> GenerationResponse:
        """Convenience method that delegates to generate().

        Some consumers may call .chat() directly. By default this
        calls self.generate(). Providers may override for custom
        chat-specific logic.
        """
        return await self.generate(request)

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self._name}')"
